# 逻辑运算

In [1]:
import numpy as np

In [2]:
# 生成10名同学5门功课的数据
score = np.random.randint(40, 100, (10,5))
score

array([[76, 92, 52, 82, 91],
       [44, 88, 53, 72, 62],
       [48, 52, 67, 86, 42],
       [90, 99, 98, 98, 81],
       [98, 81, 84, 78, 73],
       [82, 75, 83, 45, 84],
       [84, 77, 84, 96, 60],
       [54, 71, 56, 46, 56],
       [70, 47, 42, 59, 62],
       [72, 77, 82, 61, 70]])

In [3]:
# 取出最后4名同学的成绩用于逻辑判断
test = score[6:, 0:6]
test

array([[84, 77, 84, 96, 60],
       [54, 71, 56, 46, 56],
       [70, 47, 42, 59, 62],
       [72, 77, 82, 61, 70]])

In [4]:
# 逻辑判断，大于60标为True， 否则为FALSE
test > 60

array([[ True,  True,  True,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
# bool赋值，将满足条件的设置为指定的值-布尔索引
test[test>60] = 1

In [6]:
test

array([[ 1,  1,  1,  1, 60],
       [54,  1, 56, 46, 56],
       [ 1, 47, 42, 59,  1],
       [ 1,  1,  1,  1,  1]])